spring:
  application:
    name: queue
  datasource:
    url: jdbc:h2:mem:testdb
    username: test
    password: placeholder
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect